version: '3.4'

services:
  organization_search_beckend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: production
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    # Run a command against the development stage of the image
    command: npm run start:prod
    ports:
      - ${APP_PORT}:3072

  postgres:
    container_name: os_postgres
    image: postgres:latest
    volumes:
      - .:/postgres/data/os_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: